-- ════════════════════════════════════════
-- GONICEON Portfolio — Supabase Migration
-- Supabase projenizi oluşturduktan sonra bu
-- SQL'i Supabase SQL Editor'de çalıştırın.
-- ════════════════════════════════════════

-- 1. PROJECTS TABLE
create table if not exists public.projects (
  id            bigint generated by default as identity primary key,
  title         text not null,
  type          text,
  description   text,
  status        text default 'done',    -- 'done' | 'wip' | 'plan'
  stack         text,
  url           text,
  features      text[],
  order_num     int default 0,
  is_visible    boolean default true,
  created_at    timestamptz default now()
);

-- 2. MESSAGES TABLE (contact form submissions)
create table if not exists public.messages (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  subject     text,
  message     text not null,
  is_read     boolean default false,
  created_at  timestamptz default now()
);

-- 3. RLS (Row Level Security)
alter table public.projects enable row level security;
alter table public.messages enable row level security;

-- Projects: herkes okuyabilir (ana site)
create policy "projects_public_read"
  on public.projects for select
  using (is_visible = true);

-- Messages: sadece authenticated (CMS admin) okuyabilir
create policy "messages_admin_read"
  on public.messages for select
  to authenticated
  using (true);

-- Messages: herkes yazabilir (iletişim formu)
create policy "messages_public_insert"
  on public.messages for insert
  with check (true);

-- 4. INITIAL DATA — Mevcut projeler
insert into public.projects (title, type, description, status, stack, url, features, order_num) values
(
  'MEDEK — Süreç Yönetim & Sınav Analiz Sistemi',
  'Kurumsal SaaS',
  'Meslek yüksekokulları için Bologna veri çekimi, soru bazlı not girişi ve otomatik MEDEK raporlama sistemi.',
  'done',
  'Python, Supabase, PostgreSQL, RLS, Web Scraping',
  'medek.goniceon.dev/dashboard',
  ARRAY['Otomatik Bologna veri çekimi','Soru bazlı not girişi','Otomatik MEDEK raporu üretimi','Rol bazlı erişim kontrolü'],
  1
),
(
  'Kafe QR — Dijital Menü & Yönetim Sistemi',
  'Restoran Yazılımı',
  'Kafeler için QR tabanlı dijital menü. Gerçek zamanlı güncelleme, çift dil desteği ve admin paneli.',
  'done',
  'HTML/CSS/JS, Supabase, QR Kodu',
  'kafe.goniceon.dev/menu',
  ARRAY['QR kod ile anında erişim','Çift dil desteği (TR/EN)','Gerçek zamanlı ürün güncelleme','Görsel medya yönetimi'],
  2
),
(
  'AutoGuard — Otonom AI Güvenlik Sistemi',
  'Yapay Zeka',
  'RTX 5070 Ti tabanlı, TensorRT optimize güvenlik kamerası sistemi. YOLO ile gerçek zamanlı tespit, otomatik kayıt.',
  'wip',
  'Python, YOLO, TensorRT, GPU',
  'autoguard.goniceon.dev',
  ARRAY['Gerçek zamanlı nesne tespiti','GPU optimizasyonu (RTX 5070 Ti)','Otomatik olay video kaydı','AI tehdit analizi (geliştiriliyor)'],
  3
);
